### ISSUE TITLE
Test fails on html.fromstring with valid html/xml

### ISSUE THREAD

**Issue by alphatownsman** [neodb-social/neodb#5]
OS: macOS 13.1
Python: 3.10
lxml: 3.9.2

```
➜  neodb-app git:(main) ✗ python3 manage.py test --keepdb
Using existing test database for alias 'default'...
System check identified no issues (2 silenced).
...........E...E.E................E...E..E..............
======================================================================
ERROR: test_work (catalog.book.tests.DoubanBookTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 30, in _func
    func(args)
  File "/Users/henridickson/Projects/neodb-app/catalog/book/tests.py", line 188, in test_work
    p1 = SiteList.get_site_by_url(url1).get_resource_ready()
  File "/Users/henridickson/Projects/neodb-app/catalog/common/sites.py", line 108, in get_resource_ready
    resource_content = self.scrape()
  File "/Users/henridickson/Projects/neodb-app/catalog/sites/douban_book.py", line 43, in scrape
    self.html = DoubanDownloader(self.url).download().html()
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 238, in html
    return html.fromstring(self.text)  # may throw exception unexpectedly due to OS bug
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 873, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty

======================================================================
ERROR: test_scrape (catalog.game.tests.DoubanGameTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 30, in _func
    func(args)
  File "/Users/henridickson/Projects/neodb-app/catalog/game/tests.py", line 85, in test_scrape
    site.get_resource_ready()
  File "/Users/henridickson/Projects/neodb-app/catalog/common/sites.py", line 108, in get_resource_ready
    resource_content = self.scrape()
  File "/Users/henridickson/Projects/neodb-app/catalog/sites/douban_game.py", line 23, in scrape
    content = DoubanDownloader(self.url).download().html()
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 238, in html
    return html.fromstring(self.text)  # may throw exception unexpectedly due to OS bug
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 873, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty

======================================================================
ERROR: test_scrape_singleseason (catalog.tv.tests.DoubanMovieTVTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 30, in _func
    func(args)
  File "/Users/henridickson/Projects/neodb-app/catalog/tv/tests.py", line 79, in test_scrape_singleseason
    p3 = SiteList.get_site_by_url(url3).get_resource_ready()
  File "/Users/henridickson/Projects/neodb-app/catalog/common/sites.py", line 108, in get_resource_ready
    resource_content = self.scrape()
  File "/Users/henridickson/Projects/neodb-app/catalog/sites/douban_movie.py", line 69, in scrape
    content = DoubanDownloader(self.url).download().html()
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 238, in html
    return html.fromstring(self.text)  # may throw exception unexpectedly due to OS bug
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 873, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty

======================================================================
ERROR: test_works (catalog.book.tests.MultiBookSitesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 30, in _func
    func(args)
  File "/Users/henridickson/Projects/neodb-app/catalog/book/tests.py", line 221, in test_works
    p1 = SiteList.get_site_by_url(url1).get_resource_ready()  # lxml bug may break this
  File "/Users/henridickson/Projects/neodb-app/catalog/common/sites.py", line 108, in get_resource_ready
    resource_content = self.scrape()
  File "/Users/henridickson/Projects/neodb-app/catalog/sites/douban_book.py", line 43, in scrape
    self.html = DoubanDownloader(self.url).download().html()
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 238, in html
    return html.fromstring(self.text)  # may throw exception unexpectedly due to OS bug
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 873, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty

======================================================================
ERROR: test_miniseries (catalog.tv.tests.MultiTVSitesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 30, in _func
    func(args)
  File "/Users/henridickson/Projects/neodb-app/catalog/tv/tests.py", line 113, in test_miniseries
    p3 = SiteList.get_site_by_url(url3).get_resource_ready()
  File "/Users/henridickson/Projects/neodb-app/catalog/common/sites.py", line 108, in get_resource_ready
    resource_content = self.scrape()
  File "/Users/henridickson/Projects/neodb-app/catalog/sites/douban_movie.py", line 69, in scrape
    content = DoubanDownloader(self.url).download().html()
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 238, in html
    return html.fromstring(self.text)  # may throw exception unexpectedly due to OS bug
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 873, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty

======================================================================
ERROR: test_tvspecial (catalog.tv.tests.MultiTVSitesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 30, in _func
    func(args)
  File "/Users/henridickson/Projects/neodb-app/catalog/tv/tests.py", line 124, in test_tvspecial
    p3 = SiteList.get_site_by_url(url3).get_resource_ready()
  File "/Users/henridickson/Projects/neodb-app/catalog/common/sites.py", line 108, in get_resource_ready
    resource_content = self.scrape()
  File "/Users/henridickson/Projects/neodb-app/catalog/sites/douban_movie.py", line 69, in scrape
    content = DoubanDownloader(self.url).download().html()
  File "/Users/henridickson/Projects/neodb-app/catalog/common/downloaders.py", line 238, in html
    return html.fromstring(self.text)  # may throw exception unexpectedly due to OS bug
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 873, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/henridickson/Projects/neodb-env/mac-pyve/lib/python3.9/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty

----------------------------------------------------------------------
Ran 56 tests in 0.743s

FAILED (errors=6)
Preserving test database for alias 'default'...
```

**Comment by alphatownsman** [comment]
This is likely due to lxml on macOS linked to a problematic libxml2 that dosen't handle emoji or other characters. This can be confirmed by:

```
from lxml import html

txt = '<html><head><title>ok</title></head><body>®</body></html>'
print(html.fromstring(txt).xpath("//title/text()"))
txt = '<html><head><title>ok</title></head><body>😊</body></html>'
print(html.fromstring(txt).xpath("//title/text()"))
```

The fix is to [build lxml with static dependencies](https://lxml.de/build.html#building-lxml-on-macos-x).
