### ISSUE TITLE
[BUG] Error duting Database initialisation of dev setup

### ISSUE THREAD

**Issue by qilinz** [neodb-social/neodb#597]
**Describe the bug**

Hello @alphatownsman, I tried to setup development env. 

When I do: `docker compose --profile dev run --rm dev-shell neodb-init`

I met error: 
`django.db.migrations.exceptions.InconsistentMigrationHistory: Migration users.0012_apidentity is applied before its dependency users.0015_user_mastodon_last_reachable on database 'default'.
`
When i check the file, 0012 does depend on 0015. 

As it's related to db, do you have any suggestion about how i should fix it? and also for future developers? Thanks in advance!

**Comment by qilinz** [comment]
I am starting from scratch. 

when I pull images `docker compose pull`:
it showed: 
```
[+] Pulling 23/4
 ✔ neodb-db Skipped - Image is already being pulled by takahe-db                                                                       0.0s 
 ✔ takahe-db 9 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                              16.2s 
 ✔ typesense 4 layers [⣿⣿⣿⣿]      0B/0B      Pulled                                                                                   22.6s 
 ✔ redis 6 layers [⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled   
```

When i ran `docker compose --profile dev run --rm dev-shell neodb-init`

```
[+] Creating 4/0
 ✔ Container neodb-typesense-1  Running                                                                                                0.0s 
 ✔ Container neodb-redis-1      Running                                                                                                0.0s 
 ✔ Container neodb-takahe-db-1  Running                                                                                                0.0s 
 ✔ Container neodb-neodb-db-1   Running                                                                                                0.0s 
[+] Running 22/22
 ✔ dev-shell 21 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                 48.8s 
   ✔ 09f376ebb190 Pull complete                                                                                                        6.7s 
   ✔ 276709cbedc1 Pull complete                                                                                                        7.3s 
   ✔ 2e133733af76 Pull complete                                                                                                        9.0s 
   ✔ ded8879d9a79 Pull complete                                                                                                        9.0s 
   ✔ 3cf9507408dc Pull complete                                                                                                        9.8s 
   ✔ eb4cc85fd18c Pull complete                                                                                                       10.6s 
   ✔ 40457d0fbffe Pull complete                                                                                                       10.6s 
   ✔ cbf715ae70e9 Pull complete                                                                                                       13.8s 
   ✔ 7cb4e99a1d84 Pull complete                                                                                                       13.9s 
   ✔ d6c91ecafdc2 Pull complete                                                                                                       13.9s 
   ✔ aff82dc5f2de Pull complete                                                                                                       14.3s 
   ✔ 4f4fb700ef54 Pull complete                                                                                                       14.3s 
   ✔ cb84ff15d41a Pull complete                                                                                                       31.9s 
   ✔ c1e5785c9e87 Pull complete                                                                                                       32.0s 
   ✔ a9c949c2ae5f Pull complete                                                                                                       32.0s 
   ✔ 8823626a3cae Pull complete                                                                                                       32.4s 
   ✔ 46d60743feb3 Pull complete                                                                                                       32.9s 
   ✔ 5958bc494605 Pull complete                                                                                                       46.3s 
   ✔ 3cbb985e453f Pull complete                                                                                                       46.7s 
   ✔ 37daec1827f9 Pull complete                                                                                                       46.8s 
   ✔ 632a4dfad738 Pull complete                                                                                                       46.8s 
====== NeoDB ======
Version: dev-unknown debug:on
Your configuration is for My Test on mydomain.dev
NeoDB initializing...
Operations to perform:
  Apply all migrations: activities, admin, api, auth, contenttypes, core, sessions, stator, users
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/neodb/manage.py", line 21, in <module>
    main()
  File "/neodb/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/neodb-venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/neodb-venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/neodb-venv/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/neodb-venv/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/neodb-venv/lib/python3.12/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/neodb-venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 120, in handle
    executor.loader.check_consistent_history(connection)
  File "/neodb-venv/lib/python3.12/site-packages/django/db/migrations/loader.py", line 327, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration users.0012_apidentity is applied before its dependency users.0015_user_mastodon_last_reachable on database 'default'.
```

Long time no see ^^

**Comment by qilinz** [comment]
It works fine after deleting! Thanks a lot! I guess i messed it up when running command and canceling. I closed the issue^ ^
